#!/bin/sh
# gen-assets.sh — generate src/ui_assets.inc from ui/ (jb ui's source of
# truth). Build-time step (Makefile), not a runtime dependency. Each ui/
# file becomes a static const array + length via xxd -i.
set -eu
SRC="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
OUT="$SRC/../src/ui_assets.inc"

{
    echo "/* ui_assets.inc — embedded jb ui assets (ui/index.html, style.css, app.js)."
    echo "   Generated by ui/gen-assets.sh — do not edit. The ui/ directory is"
    echo "   the source of truth; rebuild with: make src/ui_assets.inc */"
    for f in index.html style.css app.js; do
        sym="jb_ui_$(printf '%s' "$f" | tr '.-' '__')"
        xxd -i "$SRC/$f" | sed \
            -e "s/^unsigned char .*\[\]/static const unsigned char ${sym}[]/" \
            -e "s/^unsigned int .*_len/static const unsigned int ${sym}_len/"
    done
} > "$OUT"
